import transform from '../transform.es6';

const source = [ { url: 'https://api.github.com/repos/stepankouba/larch/milestones/1',
    html_url: 'https://github.com/stepankouba/larch/milestones/0.1.0',
    labels_url: 'https://api.github.com/repos/stepankouba/larch/milestones/1/labels',
    id: 1238379,
    number: 1,
    title: '0.1.0',
    description: null,
    creator: 
     { login: 'stepankouba',
       id: 10066901,
       avatar_url: 'https://avatars.githubusercontent.com/u/10066901?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/stepankouba',
       html_url: 'https://github.com/stepankouba',
       followers_url: 'https://api.github.com/users/stepankouba/followers',
       following_url: 'https://api.github.com/users/stepankouba/following{/other_user}',
       gists_url: 'https://api.github.com/users/stepankouba/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/stepankouba/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/stepankouba/subscriptions',
       organizations_url: 'https://api.github.com/users/stepankouba/orgs',
       repos_url: 'https://api.github.com/users/stepankouba/repos',
       events_url: 'https://api.github.com/users/stepankouba/events{/privacy}',
       received_events_url: 'https://api.github.com/users/stepankouba/received_events',
       type: 'User',
       site_admin: false },
    open_issues: 9,
    closed_issues: 16,
    state: 'open',
    created_at: '2015-08-03T13:55:40Z',
    updated_at: '2015-10-16T20:51:58Z',
    due_on: null,
    closed_at: null },
  { url: 'https://api.github.com/repos/stepankouba/larch/milestones/2',
    html_url: 'https://github.com/stepankouba/larch/milestones/0.2.0',
    labels_url: 'https://api.github.com/repos/stepankouba/larch/milestones/2/labels',
    id: 1270943,
    number: 2,
    title: '0.2.0',
    description: null,
    creator: 
     { login: 'stepankouba',
       id: 10066901,
       avatar_url: 'https://avatars.githubusercontent.com/u/10066901?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/stepankouba',
       html_url: 'https://github.com/stepankouba',
       followers_url: 'https://api.github.com/users/stepankouba/followers',
       following_url: 'https://api.github.com/users/stepankouba/following{/other_user}',
       gists_url: 'https://api.github.com/users/stepankouba/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/stepankouba/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/stepankouba/subscriptions',
       organizations_url: 'https://api.github.com/users/stepankouba/orgs',
       repos_url: 'https://api.github.com/users/stepankouba/repos',
       events_url: 'https://api.github.com/users/stepankouba/events{/privacy}',
       received_events_url: 'https://api.github.com/users/stepankouba/received_events',
       type: 'User',
       site_admin: false },
    open_issues: 6,
    closed_issues: 2,
    state: 'open',
    created_at: '2015-08-25T07:25:42Z',
    updated_at: '2015-10-16T08:03:03Z',
    due_on: null,
    closed_at: null } ];

const template = '$..[?(@.title === "0.2.0")]';

console.log(JSON.stringify(transform(source, template), null, 4));
